[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.sort-derives-check]
command = "cargo"
args = ["sort-derives", "--check"]

[tasks.test]
command = "cargo"
args = ["test", "--verbose"]

[tasks.lint]
dependencies = ["fmt-check", "clippy"]

[tasks.ci]
dependencies = ["lint", "sort-derives-check", "test"]
